apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{cookiecutter.name | jsonify}}
  description: {{cookiecutter.description | jsonify}}
  annotations:
    github.com/project-slug: {{cookiecutter.destination.owner + "/" + cookiecutter.destination.repo}}
    jenkins.io/github-folder: {{cookiecutter.name | jsonify}}
spec:
  type: service
  lifecycle: experimental
  owner: {{cookiecutter.owner | jsonify}}
