pipeline {
    agent any 
    stages {
        stage('Build') { 
            steps {
                docker build -t test .
            }
        }
        stage('Test') { 
            steps {
                echo "test"
            }
        }
        stage('Deploy') { 
            steps {
                echo "deploy"
            }
        }
    }
}