pipeline {
    agent { dockerfile true } 
    stages {
        stage('Build') { 
            steps {
                script {
                    dockerImage = docker.build {{cookiecutter.name}}
                }
            }
        }
        stage('Test') { 
            steps {
                echo "test"
            }
        }
        stage('Deploy') { 
            steps {
                echo "deploy"
            }
        }
    }
}